### ISSUE TITLE
Notification shows thick borders with Plata GTK theme

### ISSUE THREAD

**Issue by rodrigofarias77** [BuddiesOfBudgie/budgie-desktop#55]
## Description
Notification shows thick borders with Plata GTK theme 0.9.9.

## Budgie version
Budgie 10.5.3, built with `master` (96ea41416016b82ebb847ef44ad97f42e4a3a76f), and with `fix-internal-theme` (c51d19b53cee996c7202aadd7a5f5abb1d9955fb) merged.

## Operating system
Fedora 35

## Steps to reproduce the issue
1. Switch to theme Plata
2. `notify-send foo`

## Actual result
![image](https://user-images.githubusercontent.com/130016/154778824-8048fb72-0309-46f8-bc8e-5b4e0f325f50.png)

## Expected result
![image](https://user-images.githubusercontent.com/130016/154779398-27b64bf1-11d9-4480-a5ee-fa0eeac00ffb.png)

Budgie 10.5.3, built with d53f71afb46721a67ed9831ebeedfdf31d1ec647.

**Comment by serebit** [comment]
I'm also seeing this. Paging @EbonJaeger - this seems like it could be related to the notifications dbus rewrite.

**Comment by rodrigofarias77** [comment]
Thanks, @serebit.

It is sad to see the last commit of plata-theme was on 2020-11-04. I hope tista500 is well.

I have learned about Plata from Solus. Do you know what is going to be their next default theme?

**Comment by JoshStrobl** [comment]
> I have learned about Plata from Solus. Do you know what is going to be their next default GTK theme?

We aren't the Solus developers. More appropriate to ask them. I would suggest changing to Materia.

**Comment by GZGavinZhao** [comment]
It was because commit 5c1f381. Before notification is just a Box, now it's many Boxes inside one Stack, and both the Stack and the Box have margins (from class `drop-shadow`), which causes this double-margin issue.

I can't really think of a way to solve it on Budgie's side. I think it's a problem with the theme devs. For example, most themes (including Materia) do something similar to this, which treats both left and right margin as the same:
```scss
.drop-shadow {
  margin: 16px 24px 32px; // $shadow_margin_4
  background-color: transparent;
  background-image: none;
  box-shadow: $z-depth-4;
}
```

Right now, for it to look pretty, one must not only shrink the vertical ones, but also make the left margin much greater than the right margin to account for the close button and the Box's margin.
```scss
.drop-shadow {
  margin: 6px 0px 6px 10px; // Derived from $shadow_margin_3
  background-color: transparent;
  background-image: none;
  box-shadow: $z-depth-4;
}
```
Not perfect, but much better:
![Screenshot from 2022-03-17 14-59-33](https://user-images.githubusercontent.com/74938940/158876357-d02d60a1-c84b-4d40-826b-23745d69f834.png)
